msgs:
  toSend: user@example.com
  amountToRequest: 200
  amountToSend: 100
telegram:
  accessToken: asdfsadf:Fasdfsdf
  chatId: 0101010110
pocket:
  consumerKey: asdfsdfasdf
  accessToken: 7sdfs-fdsaf-sdf
schedules:
  timers:
    - ""
    - "0 */2 * ? * *"
